# name: Build & publish containers
# # at 04:00 on base image changes

# on:
#   schedule:
#     - cron:  '0 4 * * *'

# jobs:
#   build-and-push-image:
#     runs-on: ubuntu-latest
#     strategy:
#         fail-fast: false
#         matrix:
#           include:
#             - dockerfile: ./runner/Dockerfile
#             image: seatable/python-runner-cicd
#             context: ./runner
#             base-image: python:3.11-alpine

#             - dockerfile: ./starter/Dockerfile
#             image: seatable/python-starter-cicd
#             context: ./starter
#             base-image: docker:cli

#             - dockerfile: ./scheduler/Dockerfile
#             image: seatable/python-scheduler-cicd
#             context: ./scheduler
#             base-image: phusion/baseimage:jammy-1.0.1

#     permissions:
#       contents: read
#       packages: write

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3

#       - name: Check if update available
#         id: check-starter
#         uses: lucacome/docker-image-update-checker@v1
#         with:
#           base-image: ${{ matrix.base-image}}
#           image: ${{ matrix.image }}

#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v3

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3

#       - name: Login to Docker Hub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}

#       - name: Build and push
#         uses: docker/build-push-action@v5
#         with:
#           context: ${{ matrix.context }}
#           push: true
#           file: ${{ matrix.dockerfile }}
#           tags: >
#             ${{ matrix.image }}:latest ,
#             ${{ matrix.image }}:build_onbaseimage_${{ github.run_number }} ,
#             ${{ matrix.image }}:${{ steps.get_version.outputs.version }}
#         if: steps.check.outputs.needs-updating == 'true'
