name: Build & publish containers
# on main pushes (includes merged pull requests)

on:
  push:
    branches:
      - 'main'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./runner/Dockerfile
            image: seatable/python-runner-cicd

          - dockerfile: ./starter/Dockerfile
            image: seatable/python-starter-cicd

          - dockerfile: ./scheduler/docker/Dockerfile
            image: seatable/python-scheduler-cicd

    permissions:
      contents: read
      packages: write

    steps:

      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.image }}

      - name: Debug Dockerfile Paths
        run: |
          ls -R
        working-directory: .

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: ${{ matrix.dockerfile }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
