name: Build & push containers
# "on push" includes merged pull requests

on:
  push:
    branches:
      - "release-v*.*.*"
      - "testing-v*.*.*"
    paths:
      ### set component path
      - 'runner/**'

jobs:

  matrix-init:
    runs-on: ubuntu-latest
    env:
      ### set component
      component: runner
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: >
          if [[ "${{ github.ref }}" == refs/heads/testing-v* ]]; then
            dynamic_includes='[{"dockerfile": "./${{ env.component }}/Dockerfile", "image": "seatable/seatable-python-${{ env.component }}", "context": "${{ env.component }}", "ref": "refs/heads/testing-v", "version_prefix": "testing-"}]'
          elif [[ "${{ github.ref }}" == refs/heads/release-v* ]]; then
            dynamic_includes='[{"dockerfile": "./${{ env.component }}/Dockerfile", "image": "seatable/seatable-python-${{ env.component }}", "context": "${{ env.component }}", "ref": "refs/heads/release-v", "version_prefix": ""}]'
          fi
          echo "matrix={'include': $dynamic_includes}" >> $GITHUB_OUTPUT

  # echo:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - matrix-init
  #   steps:
  #     - name: Echo previous outputs
  #       run: echo "${{ toJSON(needs.matrix-init.outputs) }}"

  build-image-on-push:
    runs-on: ubuntu-latest
    needs:
      - matrix-init
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.matrix-init.outputs.matrix) }}

    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set short git commit SHA
        id: get_commit
        run: echo "short_sha=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT
      - name: Read version files
        id: "get_version"
        run: echo "version=$(cat ./${{ matrix.context }}/version)" >> $GITHUB_OUTPUT
      - id: extract_branch_prefix
        run: echo "branch_prefix=$(echo ${{ github.ref }} | awk -F/ '{print $3}' | awk -Fv '{print $1}')v" >> $GITHUB_OUTPUT
      - id: extract_branch_version
        run: echo "branch_version=$(echo ${{ github.ref }} | awk -F/ '{print $3}' | awk -Fv '{print $2}')" >> $GITHUB_OUTPUT

      - name: Compare versions
        run: |
          if [[ "${{ steps.get_version.outputs.version }}" != "${{ steps.extract_branch_version.outputs.branch_version }}" ]]; then
            echo "Version number from version file and branch name don't match, image build aborted"
            exit 1
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push runner image
        if: ${{ startsWith(github.ref, matrix.ref) }}
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: |
            seatable/seatable-python-${{ matrix.context }}:build-${{ github.run_number }}
            seatable/seatable-python-${{ matrix.context }}:commit-${{ steps.get_commit.outputs.short_sha }}
            seatable/seatable-python-${{ matrix.context }}:${{ matrix.version_prefix }}${{ steps.get_version.outputs.version }}
          labels: |
            org.opencontainers.image.title=seatable/seatable-python-${{ matrix.context }}
            org.opencontainers.image.version=${{ matrix.version_prefix }}${{ steps.get_version.outputs.version }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ github.event.head_commit.timestamp }}
            org.opencontainers.image.authors=SeaTable
            org.opencontainers.image.url=https://www.seatable.io/
            org.opencontainers.image.documentation=https://admin.seatable.io/
            org.opencontainers.image.vendor=SeaTable
