name: Build & publish containers
# on main pushes (includes merged pull requests)

on:
  push:
    branches:
      - main
    paths:
      - 'starter/**'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:

          - dockerfile: ./starter/Dockerfile
            image: seatable/seatable-python-starter
            context: starter

    permissions:
      contents: read
      packages: write

    steps:

      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set short git commit SHA
        id: get_commit
        run: echo "short_sha=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT

      - name: Read version file
        id: "get_version"
        run: echo "version=$(cat ./${{ matrix.context }}/version)" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: |
            ${{ matrix.image }}:build_${{ github.run_number }}
            ${{ matrix.image }}:commit_${{ steps.get_commit.outputs.short_sha }}
            ${{ matrix.image }}:${{ steps.get_version.outputs.version }}-test
          labels: |
            org.opencontainers.image.title=${{ matrix.image }}
            org.opencontainers.image.description=${{ matrix.short-description }}
            org.opencontainers.image.version=${{ steps.get_version.outputs.version }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ github.event.head_commit.timestamp }}
            org.opencontainers.image.authors=SeaTable
            org.opencontainers.image.url=https://www.seatable.io/
            org.opencontainers.image.documentation=https://admin.seatable.io/
            org.opencontainers.image.vendor=SeaTable
