name: Build & push containers
# "on push" includes merged pull requests

on:
  push:
    tags:
      - "release-scheduler-v*.*.*"
      - "testing-scheduler-v*.*.*"

jobs:

###### TESTING IMAGES
  build-testing-image-on-push:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/testing-scheduler-v') }}
    strategy:
      fail-fast: false
      matrix:
        include:

          - dockerfile: ./scheduler/Dockerfile
            image: seatable/seatable-python-scheduler
            context: scheduler

    permissions:
      contents: read
      packages: write
    steps:

      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set short git commit SHA
        id: get_commit
        run: echo "short_sha=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT
      - name: Read version files
        id: "get_version"
        run: echo "version=$(cat ./${{ matrix.context }}/version)" >> $GITHUB_OUTPUT
      - id: extract_branch_prefix
        run: echo "branch_prefix=$(echo ${{ github.ref }} | awk -F/ '{print $3}' | awk -Fv '{print $1}')v" >> $GITHUB_OUTPUT
      - id: extract_branch_version
        run: echo "branch_version=$(echo ${{ github.ref }} | awk -F/ '{print $3}' | awk -Fv '{print $2}')" >> $GITHUB_OUTPUT

      - name: Compare versions
        run: |
          if [[ "${{ steps.get_version.outputs.version }}" != "${{ steps.extract_branch_version.outputs.branch_version }}" ]]; then
            echo "Version number from version file and branch name don't match, container image build aborted"
            exit 1
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push runner test release
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: |
            seatable/seatable-python-${{ matrix.context }}:build-${{ github.run_number }}
            seatable/seatable-python-${{ matrix.context }}:commit-${{ steps.get_commit.outputs.short_sha }}
            seatable/seatable-python-${{ matrix.context }}:testing-${{ steps.get_version.outputs.version }}
          labels: |
            org.opencontainers.image.title=seatable/seatable-python-${{ matrix.context }}
            org.opencontainers.image.version=testing-v${{ steps.get_version.outputs.version }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ github.event.head_commit.timestamp }}
            org.opencontainers.image.authors=SeaTable
            org.opencontainers.image.url=https://www.seatable.io/
            org.opencontainers.image.documentation=https://admin.seatable.io/
            org.opencontainers.image.vendor=SeaTable


###### RELEASE IMAGES
  build-release-image-on-push:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/release-scheduler-v') }}
    strategy:
      fail-fast: false
      matrix:
        include:

          - dockerfile: ./scheduler/Dockerfile
            image: seatable/seatable-python-scheduler
            context: scheduler

    permissions:
      contents: read
      packages: write
    steps:

      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set short git commit SHA
        id: get_commit
        run: echo "short_sha=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT
      - name: Read version files
        id: "get_version"
        run: echo "version=$(cat ./${{ matrix.context }}/version)" >> $GITHUB_OUTPUT
      - id: extract_branch_prefix
        run: echo "branch_prefix=$(echo ${{ github.ref }} | awk -F/ '{print $3}' | awk -Fv '{print $1}')v" >> $GITHUB_OUTPUT
      - id: extract_branch_version
        run: echo "branch_version=$(echo ${{ github.ref }} | awk -F/ '{print $3}' | awk -Fv '{print $2}')" >> $GITHUB_OUTPUT

      - name: Compare versions
        run: |
          if [[ "${{ steps.get_version.outputs.version }}" != "${{ steps.extract_branch_version.outputs.branch_version }}" ]]; then
            echo "Version number from version file and branch name don't match, container image build aborted"
            exit 1
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push runner release release
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: |
            seatable/seatable-python-${{ matrix.context }}:build-${{ github.run_number }}
            seatable/seatable-python-${{ matrix.context }}:commit-${{ steps.get_commit.outputs.short_sha }}
            seatable/seatable-python-${{ matrix.context }}:${{ steps.get_version.outputs.version }}
          labels: |
            org.opencontainers.image.title=seatable/seatable-python-${{ matrix.context }}
            org.opencontainers.image.version=v${{ steps.get_version.outputs.version }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ github.event.head_commit.timestamp }}
            org.opencontainers.image.authors=SeaTable
            org.opencontainers.image.url=https://www.seatable.io/
            org.opencontainers.image.documentation=https://admin.seatable.io/
            org.opencontainers.image.vendor=SeaTable
