name: Build & publish containers
# on main pushes (includes merged pull requests)

on:
  push:
    branches:
      - 'main'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./runner/Dockerfile
            image: seatable/python-runner-cicd
            context: ./runner
            short-description: "Runner image for SeaTable Python scripts"

          - dockerfile: ./starter/Dockerfile
            image: seatable/python-starter-cicd
            context: ./starter
            short-description: "Starter image for SeaTable Python scripts"

          - dockerfile: ./scheduler/Dockerfile
            image: seatable/python-scheduler-cicd
            context: ./scheduler
            short-description: "Scheduler image for SeaTable Python scripts"

    permissions:
      contents: read
      packages: write

    steps:

      - name: Add SHORT_SHA env property with commit short sha
        id: set_short_sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ matrix.image }}
          enable-url-completion: true
          readme-filepath: ./dockerhub-description.md
          short-description: ${{ matrix.short-description }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          push: true
          file: ${{ matrix.dockerfile }}
          tags: >
            ${{ matrix.image }}:latest ,
            ${{ matrix.image }}:build_${{ github.run_number }} ,
            ${{ matrix.image }}:commit_${{ steps.set_short_sha.outputs.SHORT_SHA }}
