name: Cron docker scout image scan

on:

  # schedule:
  #   - cron: '0 0 * * *' # Runs every day at 00:00 GMT

  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    # The trivy Github Action does not support scanning multiple images, so we use the
    # official Trivy image instead, override default entrypoint and run
    # Trivy for every container image in the list. Fail if any image has vulnerabilities.
    - name: Scan images for CRITICAL vulnerabilities
      uses: docker://ghcr.io/aquasecurity/trivy
      with:
        entrypoint: /bin/sh
        args: -c "trivy image --clear-cache; for img in seatable/seatable-python-runner@sha256:1a77508f02c84aeeb5dbdbf657642d78cba0083e979b2f0fc25ebe737bbb7ef4; do trivy image --exit-code 1 --severity CRITICAL --no-progress $img; done"