name: Cron docker scout image scan

# on:
#   schedule:
#     - cron: '0 0 * * *' # Runs every day at 00:00 GMT

  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker_image: ['seatable/seatable-python-runner', 'seatable/seatable-python-scheduler', 'seatable/seatable-python-starter']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # - name: Extract latest short sha
    #   id: get_commit
    #   run: |
    #     git fetch --tags
    #     latest_tag=$(git tag --sort=-creatordate | grep -E '^(testing|release)-' | head -n  1)
    #     echo "latest_short_sha=$(git rev-parse --short $latest_tag)"" >> $GITHUB_OUTPUT

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Fetch and sort Docker tags
      run: |
        docker pull ${{ matrix.docker_image }}
        docker images --format "{{.Tag}} {{.CreatedSince}}" your-image-name | sort -r
      shell: bash

    # - name: Docker Scout
    #   uses: docker/scout-action@v1
    #   with:
    #     command: cves,recommendations,compare
    #     image: ${{ matrix.docker_image }}:commit-${{ steps.get_commit.outputs.latest_short_sha }}
    #     to-latest: true
    #     ignore-base: false
    #     ignore-unchanged: true
    #     only-fixed: true
    #     only-severities: critical,high
