name: Python code quality

on:
  push:
    branches:
      - '*'

jobs:
  scheduler-python-code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint black
      - name: Run Black
        run: |
          black --check --diff .
      - name: Run pylint
        run: |
          SOURCE_PATH=$GITHUB_WORKSPACE
          bash $GITHUB_WORKSPACE/python-code-quality/pylint-scheduler.sh

  starter-python-code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint black
      - name: Run Black
        run: |
          black --check --diff .
      - name: Run pylint
        run: |
          SOURCE_PATH=$GITHUB_WORKSPACE
          bash $GITHUB_WORKSPACE/python-code-quality/pylint-starter.sh
